services:
  - type: web
    name: tradeprint-eco
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn tradeprint_project.wsgi --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.5
    # Uncomment the following lines to use a managed PostgreSQL database
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: tradeprint-db
    #     property: connectionString

# Uncomment the following section to create a PostgreSQL database
# databases:
#   - name: tradeprint-db
#     databaseName: tradeprint
#     user: tradeprint
